name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: master
        ref: master
    - uses: actions/checkout@v3
      with:
        path: content
        ref: content
    - run: |
        cd content
        pip install --break-system-packages -r requirements.txt
        pelican -o ../master -s pelicanconf.py
        cd ../master
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add . && git commit -m "Build $(date)" && git push
